### ISSUE TITLE
4 - Analytics Engeneering with dbt

### ISSUE THREAD

**Issue by K0nkere** [K0nkere/DE-Zoomcamp#4]
### [dbt on docker image](https://docs.getdbt.com/docs/get-started/docker-install)

**Comment by K0nkere** [comment]
### Creating dbt project
Clone the repo of `starter project`
```
git clone https://github.com/dbt-labs/dbt-starter-project
```

**Comment by K0nkere** [comment]
#### dbt-project.yaml
there is in the project folder 
```
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dezoomcamp'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'pg-zoomcamp'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dezoomcamp:
    # Config indicated by + and applies to all files under models/example/
# we want to build staging models as views
    staging:
      materialized: view
# we want to build core models as tables
    core:
      materialized: table

vars:
  payment_type_values: [1, 2, 3, 4, 5, 6]
```
